// <auto-generated />
using System;
using EFCorePreview6Bugs;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFCorePreview6Bugs.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview6.19304.10");

            modelBuilder.Entity("EFCorePreview6Bugs.Models.NuGetFeed", b =>
                {
                    b.Property<int>("NuGetFeedId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ApiKey");

                    b.Property<DateTimeOffset>("Created");

                    b.Property<string>("FeedId")
                        .HasMaxLength(200);

                    b.Property<string>("Name");

                    b.Property<int?>("ProjectId");

                    b.Property<bool>("PublishingEnabled");

                    b.Property<DateTimeOffset?>("Updated");

                    b.HasKey("NuGetFeedId");

                    b.HasIndex("ProjectId");

                    b.ToTable("NuGetFeeds");
                });

            modelBuilder.Entity("EFCorePreview6Bugs.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ProjectId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("EFCorePreview6Bugs.Models.ProjectAccessRight", b =>
                {
                    b.Property<int>("ProjectId");

                    b.Property<string>("RightName")
                        .HasMaxLength(30);

                    b.Property<bool>("Allowed");

                    b.HasKey("ProjectId", "RightName");

                    b.ToTable("ProjectAccessRights");
                });

            modelBuilder.Entity("EFCorePreview6Bugs.Models.ProjectTag", b =>
                {
                    b.Property<int>("ProjectTagId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .HasMaxLength(30);

                    b.Property<int>("ProjectId");

                    b.HasKey("ProjectTagId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectTags");
                });

            modelBuilder.Entity("EFCorePreview6Bugs.Models.NuGetFeed", b =>
                {
                    b.HasOne("EFCorePreview6Bugs.Models.Project", "Project")
                        .WithMany("NuGetFeeds")
                        .HasForeignKey("ProjectId");
                });

            modelBuilder.Entity("EFCorePreview6Bugs.Models.ProjectAccessRight", b =>
                {
                    b.HasOne("EFCorePreview6Bugs.Models.Project", "Project")
                        .WithMany("AccessRights")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EFCorePreview6Bugs.Models.ProjectTag", b =>
                {
                    b.HasOne("EFCorePreview6Bugs.Models.Project", "Project")
                        .WithMany("Tags")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
